---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: hashicorp/terraform
    tag: 0.11.13

inputs:
  - name: code

outputs:
  - name: initialized-code

params:
  WORKING_DIR: .

run:
  path: sh
  args:
    - -c
    - |
      set -euo pipefail

      BASEDIR=$PWD

      cp -r code/. initialized-code/

      # Move to the directory which holds the main code
      cd initialized-code/$WORKING_DIR

      terraform init
